version: "3"
services:
  threads:
    image: textile/go-threads:1ef50f7
    environment:
      - THREADS_APIADDR=/ip4/0.0.0.0/tcp/5000
      - THREADS_APIPROXYADDR=/ip4/0.0.0.0/tcp/5050
    ports:
      - "4007:4006"
      - "4007:4006/udp"
      - "127.0.0.1:4002:5000"
      - "127.0.0.1:4052:5050"
  ipfs:
    image: textile/go-ipfs:v0.8.0-m1
    environment:
      - IPFS_PROFILE=test
    ports:
      - "127.0.0.1:5012:5001"