name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buf:
    name: Buf
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        run: git checkout master
      - name: checkout
        uses: actions/checkout@v1
      - name: make local
        run: make buf-local
  buck:
    name: Buck CLI
    runs-on: ubuntu-latest
    container: golang:1.16.0-buster
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: make build-buck
  buckd:
    name: Buck Daemon
    runs-on: ubuntu-latest
    container: golang:1.16.0-buster
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: make build-buckd
